### ISSUE TITLE
BluetoothBytesParser array index out of bounds

### ISSUE THREAD

**Issue by imsunburnt** [weliem/blessed-android-coroutines#19]
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-9
    Process: com.welie.blessedexample, PID: 22490
    java.lang.ArrayIndexOutOfBoundsException: length=7; index=7
        at com.welie.blessed.BluetoothBytesParser.setCurrentTime(BluetoothBytesParser.kt:559)
        at com.welie.blessedexample.BluetoothHandler$handlePeripheral$1.invokeSuspend(BluetoothHandler.kt:54)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

value size is reset to 7 in call to setDateTime() after being set to 10 in setCurrentTime()

    fun setCurrentTime(calendar: Calendar): Boolean {
        value = ByteArray(10)
        setDateTime(calendar)
        value[7] = ((calendar[Calendar.DAY_OF_WEEK] + 5) % 7 + 1).toByte()
        value[8] = (calendar[Calendar.MILLISECOND] * 256 / 1000).toByte()
        value[9] = 1
        return true
    }

    /**
     * Sets the byte array to represent the current date in CurrentTime format
     *
     * @param calendar the calendar object representing the current date
     * @return flase if the calendar object was null, otherwise true
     */
    fun setDateTime(calendar: Calendar): Boolean {
        value = ByteArray(7)
        value[0] = calendar[Calendar.YEAR].toByte()
        value[1] = (calendar[Calendar.YEAR] shr 8).toByte()
        value[2] = (calendar[Calendar.MONTH] + 1).toByte()
        value[3] = calendar[Calendar.DATE].toByte()
        value[4] = calendar[Calendar.HOUR_OF_DAY].toByte()
        value[5] = calendar[Calendar.MINUTE].toByte()
        value[6] = calendar[Calendar.SECOND].toByte()
        return true
    }

**Comment by weliem** [comment]
Good catch! Fixed in 9c3bcff4761051962ab9d4e404d69b515b3ac3ad
