### ISSUE TITLE
IllegalStateException BT Adapter is not turned ON

### ISSUE THREAD

**Issue by thaidv-earable** [weliem/blessed-android-coroutines#42]
OS version: Android 13, 14
Device: Pixel 5, Pixel 6, Pixel 7 Pro
Background: Yes
Rooted: No
Blessed-android-coroutines: 0.4.0

```
Fatal Exception: java.lang.IllegalStateException: BT Adapter is not turned ON
       at android.bluetooth.le.BluetoothLeUtils.checkAdapterStateOn(BluetoothLeUtils.java:160)
       at android.bluetooth.le.BluetoothLeScanner.stopScan(BluetoothLeScanner.java:310)
       at com.welie.blessed.BluetoothCentralManager.stopScan(BluetoothCentralManager.kt:415)
       at com.welie.blessed.BluetoothCentralManager.setScanTimer$lambda-8(BluetoothCentralManager.kt:700)
       at com.welie.blessed.BluetoothCentralManager.$r8$lambda$nxpJqov4C8B70Ry3ZyS3UMxi7p0()
       at com.welie.blessed.BluetoothCentralManager$$ExternalSyntheticLambda2.run(:2)
       at android.os.Handler.handleCallback(Handler.java:959)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loopOnce(Looper.java:232)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:8532)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ExecInit.main(ExecInit.java:50)
       at com.android.internal.os.RuntimeInit.nativeFinishInit(RuntimeInit.java)
       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

I see this issue occur in `blessed-android` with same problem is https://github.com/weliem/blessed-android/issues/169 
and have fixed in https://github.com/weliem/blessed-android/pull/171. Do you have plan update this issue to `blessed-android-coroutines`

**Comment by weliem** [comment]
Fixed by b91c52a8ca580beeb1ac6b346196303af896ef45
